apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-pv
spec:
  capacity: 
    storage: 1Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/task
    type: DirectoryOrCreate