apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
spec:
  volumeName: tasks-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 500Ki